### ISSUE TITLE
Building multiple binaries

### ISSUE THREAD

**Issue by jweslley** [gobuild-old/gobuild2#5]
Hi guys, 

I developed a set of command-line statistics tools ([stats-tools](https://github.com/jweslley/stats-tools)) and I wanna distribute them using gobuild for the sake of simplicity. :) However I dont know how to configure it in order to build all the binaries at once. Is this possible? If so, can someone help me?

Actually, I'm using a Makefile and [gox](https://github.com/mitchellh/gox) to build the binaries.

**Comment by lunny** [comment]
I think currently it does not support multiple binaries for one build. @codeskyblue

**Comment by codeskyblue** [comment]
I make the gobuild2 slave support multiple binaries for one build.
But still got serve to support todo.

在 2014年6月14日，9:40，Lunny Xiao notifications@github.com 写道：

**Comment by codeskyblue** [comment]
@jweslley It seems there is a way. I will pull request to you if I figured it out.

**Comment by jweslley** [comment]
thanks in advance @codeskyblue =)

**Comment by codeskyblue** [comment]
it should be ok now.
2014-6-14 PM9:22于 "Jonhnny Weslley" notifications@github.com写道：

**Comment by jweslley** [comment]
Great @codeskyblue . Thanks!
Just one more thing, why amd64 binaries are not available!?

**Comment by codeskyblue** [comment]
Because I tested that i386 can run on amd64. So I only left i386. I donot know the value of generating a amd64 program!

**Comment by jweslley** [comment]
You are right. i386 binaries can be run in amd64 machines. However, they can produce unexpected results depending on numeric types used. Specially, `int` and `unit` which are architecture-dependent.

http://golang.org/ref/spec#Numeric_types

**Comment by codeskyblue** [comment]
sorry, a little busy these days. Already added amd64(windows, linux) support.

**Comment by jweslley** [comment]
Thanks @codeskyblue ! I would like to help you on getting gobuild better. What issues could I work on?

**Comment by codeskyblue** [comment]
@jweslley  thanks for your sincerely reply. Actually this project readlly got so many things todo. 
- [x] css page UI(will finish by fuxiaohei)
- [x] cgo support by go1.3
- [x] top download page
- [ ] support wget download eg: `wget http://gobuild.io/github.com/beego/bee/linux/amd64 -O bee.zip`
- [ ] support triggered by github
- [ ] support trigger other platform
- [x] better badge
- [ ] show README in repository page
- [ ] support restrict platform in `.gobuild.yml`
- [ ] API document

you can study how to support cgo crosscompile with go1.3 if you have time.

**Comment by codeskyblue** [comment]
not maintained
