### ISSUE TITLE
Fancy badges

### ISSUE THREAD

**Issue by guilhem** [gobuild-old/gobuild2#9]
according to #5 this is on TODO ;)

Here is a service who can help: http://shields.io/
and with GH here: https://github.com/badges/shields

**Comment by codeskyblue** [comment]
this is nice. Got https:// address ?

**Comment by guilhem** [comment]
@codeskyblue I just test this https://img.shields.io/hexpm/l/plug.svg and seems to work ![https image](https://img.shields.io/hexpm/l/plug.svg)

**Comment by codeskyblue** [comment]
@guilhem added in gobuild3
